[build-system]
requires = ["setuptools>=83.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "certbot-plugin-edgedns"
version = "0.3.0"
description = "Akamai Edge DNS Authenticator plugin for Certbot"
readme = "README.rst"
requires-python = ">=3.12"
license = "Apache-2.0"
license-files = ["LICENSE.txt"]
authors = [
    {name = "Ed Lynes [Akamai Technologies, Inc]", email = "elynes@akamai.com"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Plugins",
    "Intended Audience :: System Administrators",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Security",
    "Topic :: System :: Installation/Setup",
    "Topic :: System :: Networking",
    "Topic :: System :: Systems Administration",
    "Topic :: Utilities",
]
keywords = ["certbot", "edgedns"]
dependencies = [
    "acme>=5.7.0",
    "certbot>=5.7.0",
    "requests>=2.34.2",
    "urllib3>=2.7.0",
    "edgegrid-python>=2.0.7",
    "zope.interface>=8.5",
]

[project.urls]
Homepage = "https://github.com/akamai/certbot-plugin-edgedns"

[project.optional-dependencies]
docs = [
    "Sphinx>=9.1.0",
    "sphinx_rtd_theme>=3.1.0",
]
test = [
    "requests_mock>=1.12.1",
    "mock>=5.2.0",
]

[project.entry-points."certbot.plugins"]
edgedns = "certbot_plugin_edgedns.edgedns:Authenticator"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false
